cairo: Reinstate 0001-Reinstate-cairo-directfd.patch
Comment out unused slim_hidden_def() and slim_hidden_proto() functions.

../sources/cairo-1.18.4/src/cairo-directfb-surface.c:545:1: error: type defaults to 'int' in declaration of 'slim_hidden_def' [-Wimplicit-int]

../sources/cairo-1.18.4/src/cairo-directfb-surface.c:56:1: error: type defaults to 'int' in declaration of 'slim_hidden_proto' [-Wimplicit-int]